// Initial seed data for the healthcare prototype
export const seedData = {
  hospitals: [
    { id: "h1", name: "MediCare General Hospital", city: "Dhaka" },
    { id: "h2", name: "Riverside Medical Center", city: "Chattogram" },
  ],
  doctors: [
    {
      id: "d1",
      name: "Dr. Sarah Chen",
      specialty: "General Medicine",
      hospitalIds: ["h1", "h2"],
      phone: "555-0101",
    },
    {
      id: "d2",
      name: "Dr. Michael Roberts",
      specialty: "Cardiology",
      hospitalIds: ["h1"],
      phone: "555-0102",
    },
    {
      id: "d3",
      name: "Dr. Priya Patel",
      specialty: "Pediatrics",
      hospitalIds: ["h2"],
      phone: "555-0103",
    },
  ],
  nurses: [
    { id: "n1", name: "Nurse Emily Davis", hospitalId: "h1", shift: "Day" },
    { id: "n2", name: "Nurse James Wilson", hospitalId: "h1", shift: "Night" },
    { id: "n3", name: "Nurse Anna Lopez", hospitalId: "h2", shift: "Day" },
  ],
  patients: [
    {
      id: "p1",
      name: "John Smith",
      phone: "555-1001",
      age: 45,
      gender: "Male",
      createdAt: new Date().toISOString(),
    },
    {
      id: "p2",
      name: "Maria Garcia",
      phone: "555-1002",
      age: 32,
      gender: "Female",
      createdAt: new Date().toISOString(),
    },
  ],
  companies: [
    { id: "c1", name: "Beximco Pharmaceuticals Ltd.", email: "info@beximco.com" },
    { id: "c2", name: "Square Pharmaceuticals Ltd.", email: "contact@squarepharma.com.bd" },
    { id: "c3", name: "Healthcare Pharmaceuticals Ltd.", email: "info@healthcarepharma.com" },
    { id: "c4", name: "Incepta Pharmaceuticals Ltd.", email: "info@inceptapharma.com" },
    { id: "c5", name: "ACI Limited", email: "info@aci-bd.com" },
    { id: "c6", name: "Renata Limited", email: "info@renata.com.bd" },
    { id: "c7", name: "Opsonin Pharma Limited", email: "info@opsonin-pharma.com" },
  ],
  medicines: [
    {
      id: "m1",
      brand: "Napa",
      name: "Napa 500mg",
      type: "Tablet",
      strength: "500 mg",
      generic: "Paracetamol",
      company: "Beximco Pharmaceuticals Ltd.",
      companyId: "c1",
      price: "1.20 BDT",
      packSize: "10 x 10's pack",
      usage: "Fever, mild to moderate pain, headache, migraine, toothache, osteoarthritis.",
      dosage: "500mg every 4–6 hours as needed.",
      sideEffects: "Nausea, skin rash, allergic reaction.",
      indication:
        "Used for fever, mild to moderate pain including headache, migraine, toothache, backache, neuralgia, sore throat, period pain, aches and pains of colds and flu, and pain of osteoarthritis.",
      adultDose: "500–1000 mg every 4–6 hours as needed. Maximum 4 g per day.",
      childDose:
        "6–12 years: 250–500 mg every 4–6 hours, max 4 doses in 24 hours. 1–5 years: 120–250 mg. Under 3 months: only on doctor's advice.",
      renalDose:
        "CrCl 10–50 mL/min: every 6 hours. CrCl < 10 mL/min: every 8 hours. Dose adjustment may be required.",
      administration: "May be taken with or without food. Swallow tablet whole with water.",
      contraindications:
        "Hypersensitivity to paracetamol or any component of the formulation. Severe hepatic impairment.",
      precautions:
        "Use cautiously in patients with hepatic or renal impairment, alcohol dependence, chronic malnutrition, and dehydration.",
      pregnancy:
        "Pregnancy Category B. Considered safe during pregnancy at therapeutic doses for short duration. Excreted in breast milk in small amounts.",
      interactions:
        "May enhance anticoagulant effect of warfarin with prolonged use. Alcohol increases hepatotoxic risk. Cholestyramine reduces absorption.",
      adverse:
        "Generally well tolerated. Rare: skin rash, blood dyscrasias, hepatotoxicity in overdose.",
      mechanism:
        "Inhibits prostaglandin synthesis in the central nervous system and peripherally blocks pain impulse generation. Antipyretic effect via hypothalamic heat-regulating center.",
      storage: "Store below 30°C in a dry place, protected from light. Keep out of reach of children.",
      warnings: ["Liver"],
      variants: [
        { label: "120 mg / 5 ml Syrup", strength: "120 mg/5 ml", type: "Syrup" },
        { label: "500 mg Tablet", strength: "500 mg", type: "Tablet" },
        { label: "250 mg Suppository", strength: "250 mg", type: "Suppository" },
        { label: "80 mg/ml Drops", strength: "80 mg/ml", type: "Drops" },
      ],
      status: "Approved",
    },
    {
      id: "m2",
      brand: "Ace",
      name: "Ace 500mg",
      type: "Tablet",
      strength: "500 mg",
      generic: "Paracetamol",
      company: "Square Pharmaceuticals Ltd.",
      companyId: "c2",
      price: "1.21 BDT",
      packSize: "20 x 10's pack",
      usage: "Fever, headache, body ache, post-operative pain.",
      dosage: "1–2 tablets every 4–6 hours.",
      sideEffects: "Rare: nausea, rash.",
      indication: "Fever, headache, body ache, postoperative pain, dental pain, dysmenorrhea.",
      adultDose: "500–1000 mg every 4–6 hours. Max 4 g/day.",
      childDose: "10–15 mg/kg every 4–6 hours. Max 60 mg/kg/day.",
      renalDose: "Increase dosing interval in severe renal impairment.",
      administration: "Oral. May be taken with or without food.",
      contraindications: "Known hypersensitivity. Severe hepatic dysfunction.",
      precautions: "Caution in chronic alcoholism, hepatic or renal impairment.",
      pregnancy: "Category B. Safe in pregnancy at recommended doses.",
      interactions: "Warfarin (potentiation), chronic alcohol (hepatotoxicity).",
      adverse: "Rash, urticaria, rare hepatotoxicity in overdose.",
      mechanism: "Central inhibition of cyclooxygenase. Acts on hypothalamus for antipyresis.",
      storage: "Store below 30°C, protected from light and moisture.",
      warnings: ["Liver"],
      variants: [
        { label: "120 mg / 5 ml Syrup", strength: "120 mg/5 ml", type: "Syrup" },
        { label: "500 mg Tablet", strength: "500 mg", type: "Tablet" },
        { label: "665 mg XR Tablet", strength: "665 mg", type: "Tablet" },
      ],
      status: "Approved",
    },
    {
      id: "m3",
      brand: "Seclo",
      name: "Seclo 20mg",
      type: "Capsule",
      strength: "20 mg",
      generic: "Omeprazole",
      company: "Square Pharmaceuticals Ltd.",
      companyId: "c2",
      price: "7.04 BDT",
      packSize: "3 x 10's pack",
      usage: "Acid reflux, peptic ulcer, GERD.",
      dosage: "20–40 mg once daily before breakfast.",
      sideEffects: "Headache, diarrhea, abdominal pain.",
      indication:
        "Duodenal ulcer, gastric ulcer, gastro-oesophageal reflux disease (GERD), Zollinger-Ellison syndrome, NSAID-associated gastric and duodenal ulcers, H. pylori eradication (with antibiotics).",
      adultDose:
        "GERD: 20 mg once daily for 4–8 weeks. Peptic ulcer: 20 mg once daily for 4 weeks (DU) or 8 weeks (GU). Zollinger-Ellison: 60 mg once daily, adjust as needed.",
      childDose:
        "1–16 years: weight-based. 5–10 kg: 5 mg/day. 10–20 kg: 10 mg/day. >20 kg: 20 mg/day.",
      renalDose: "No dose adjustment necessary.",
      administration:
        "Take 30–60 minutes before meal, preferably in the morning. Swallow whole, do not crush or chew.",
      contraindications:
        "Hypersensitivity to omeprazole or substituted benzimidazoles. Coadministration with rilpivirine, nelfinavir.",
      precautions:
        "Long-term use may increase risk of fractures, B12 deficiency, hypomagnesaemia, and C. difficile infection. Reassess need for prolonged therapy.",
      pregnancy:
        "Pregnancy Category C. Use only if clearly needed. Excreted in breast milk; caution advised.",
      interactions:
        "Reduces clopidogrel activity. Increases levels of diazepam, phenytoin, warfarin. Reduces absorption of ketoconazole, itraconazole.",
      adverse:
        "Common: headache, diarrhea, nausea, flatulence. Rare: hepatic dysfunction, interstitial nephritis, hypomagnesaemia.",
      mechanism:
        "Proton pump inhibitor. Irreversibly inhibits H+/K+-ATPase in gastric parietal cells, suppressing basal and stimulated gastric acid secretion.",
      storage: "Store below 30°C, in a dry place, protected from light.",
      warnings: ["Pregnancy", "Kidney"],
      variants: [
        { label: "20 mg Capsule", strength: "20 mg", type: "Capsule" },
        { label: "40 mg Capsule", strength: "40 mg", type: "Capsule" },
        { label: "40 mg IV Injection", strength: "40 mg", type: "Injection" },
      ],
      status: "Approved",
    },
    {
      id: "m4",
      brand: "Monas",
      name: "Monas 10mg",
      type: "Tablet",
      strength: "10 mg",
      generic: "Montelukast Sodium",
      company: "Healthcare Pharmaceuticals Ltd.",
      companyId: "c3",
      price: "12.00 BDT",
      packSize: "3 x 10's pack",
      usage: "Asthma, allergic rhinitis prophylaxis.",
      dosage: "10 mg once daily in the evening.",
      sideEffects: "Headache, abdominal pain, mood changes.",
      indication:
        "Prophylaxis and chronic treatment of asthma in adults and children. Symptomatic relief of seasonal and perennial allergic rhinitis. Exercise-induced bronchoconstriction.",
      adultDose: "10 mg once daily, taken in the evening.",
      childDose: "6–14 years: 5 mg chewable tablet once daily. 2–5 years: 4 mg chewable/granules.",
      renalDose: "No dose adjustment required in renal impairment.",
      administration:
        "Oral. For asthma: take in the evening. For EIB: at least 2 hours before exercise.",
      contraindications: "Hypersensitivity to montelukast or any component of the formulation.",
      precautions:
        "Not for acute asthma attacks. Monitor for neuropsychiatric events including agitation, depression, suicidal ideation. Caution in phenylketonuria (chewable tablets contain aspartame).",
      pregnancy:
        "Pregnancy Category B. Use only if clearly needed. Excreted in breast milk; caution advised.",
      interactions:
        "Phenobarbital and rifampicin may reduce montelukast levels. Potent CYP2C8 inducers may decrease efficacy.",
      adverse:
        "Common: headache, abdominal pain, dyspepsia, dizziness, fatigue. Rare: neuropsychiatric events, Churg-Strauss syndrome, hepatic dysfunction.",
      mechanism:
        "Selective leukotriene receptor antagonist that blocks the action of leukotriene D4 at the CysLT1 receptor, reducing bronchoconstriction and inflammation.",
      storage: "Store below 30°C, protected from light and moisture.",
      warnings: ["Pregnancy"],
      variants: [
        { label: "4 mg Chewable", strength: "4 mg", type: "Tablet" },
        { label: "5 mg Chewable", strength: "5 mg", type: "Tablet" },
        { label: "10 mg Tablet", strength: "10 mg", type: "Tablet" },
      ],
      status: "Approved",
    },
    {
      id: "m5",
      brand: "Cef-3",
      name: "Cef-3 200mg",
      type: "Capsule",
      strength: "200 mg",
      generic: "Cefixime Trihydrate",
      company: "Square Pharmaceuticals Ltd.",
      companyId: "c2",
      price: "30.00 BDT",
      packSize: "1 x 6's pack",
      usage: "Bacterial infections including UTI, otitis media, pharyngitis.",
      dosage: "200 mg twice daily or 400 mg once daily.",
      sideEffects: "Diarrhea, nausea, abdominal pain.",
      indication:
        "Uncomplicated urinary tract infections, otitis media, pharyngitis, tonsillitis, acute bronchitis, uncomplicated gonorrhoea, typhoid fever.",
      adultDose: "200 mg every 12 hours or 400 mg once daily for 7 days.",
      childDose: "6 months and older: 8 mg/kg/day in single or two divided doses.",
      renalDose:
        "CrCl 21–60 mL/min: 75% of standard dose. CrCl < 20 mL/min or dialysis: 50% of standard dose.",
      administration: "Oral. May be taken with or without food.",
      contraindications:
        "Known hypersensitivity to cefixime, cephalosporins, or any component. Caution in penicillin allergy.",
      precautions:
        "Cross-sensitivity with penicillins (5–10%). Pseudomembranous colitis may occur. Adjust dose in renal impairment. Prolonged use may cause superinfection.",
      pregnancy:
        "Pregnancy Category B. Use only when clearly indicated. Caution while breastfeeding.",
      interactions:
        "Probenecid increases cefixime levels. Carbamazepine levels may rise. May reduce efficacy of oral contraceptives.",
      adverse:
        "Common: diarrhea, nausea, abdominal pain, dyspepsia. Rare: pseudomembranous colitis, Stevens-Johnson syndrome, hepatic dysfunction.",
      mechanism:
        "Third-generation cephalosporin. Inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins, leading to bacterial cell lysis.",
      storage: "Store below 30°C in a dry place, protected from light and moisture.",
      warnings: ["Kidney"],
      variants: [
        { label: "100 mg / 5 ml Suspension", strength: "100 mg/5 ml", type: "Suspension" },
        { label: "200 mg Capsule", strength: "200 mg", type: "Capsule" },
        { label: "400 mg Capsule", strength: "400 mg", type: "Capsule" },
      ],
      status: "Approved",
    },
    {
      id: "m6",
      brand: "Sergel",
      name: "Sergel 40mg",
      type: "Capsule",
      strength: "40 mg",
      generic: "Esomeprazole Magnesium Trihydrate",
      company: "Healthcare Pharmaceuticals Ltd.",
      companyId: "c3",
      price: "11.00 BDT",
      packSize: "3 x 10's pack",
      usage: "GERD, peptic ulcer, NSAID-induced ulcer.",
      dosage: "20–40 mg once daily before breakfast.",
      sideEffects: "Headache, diarrhea, dry mouth.",
      indication:
        "GERD, healing and maintenance of erosive oesophagitis, peptic ulcer disease, prevention and healing of NSAID-associated gastric ulcers, H. pylori eradication therapy, Zollinger-Ellison syndrome.",
      adultDose:
        "GERD: 20–40 mg once daily for 4–8 weeks. NSAID ulcer prophylaxis: 20 mg once daily.",
      childDose:
        "1–11 years (>20 kg): 10 mg once daily. 12–17 years: 20–40 mg once daily.",
      renalDose: "No dose adjustment in mild to moderate renal impairment.",
      administration:
        "Take at least 1 hour before meals. Swallow capsule whole or open and mix granules with water.",
      contraindications: "Hypersensitivity to esomeprazole or substituted benzimidazoles.",
      precautions:
        "Long-term therapy may cause atrophic gastritis, B12 deficiency, hypomagnesaemia, fractures of hip, wrist or spine.",
      pregnancy: "Pregnancy Category B. Use during breastfeeding only if benefit outweighs risk.",
      interactions:
        "Reduces clopidogrel activity. Increases methotrexate, diazepam, warfarin levels. Reduces absorption of ketoconazole, atazanavir, iron salts.",
      adverse:
        "Common: headache, diarrhea, abdominal pain, nausea, flatulence, dry mouth. Rare: hepatitis, hypomagnesaemia, interstitial nephritis.",
      mechanism:
        "S-isomer of omeprazole. Proton pump inhibitor that suppresses gastric acid secretion by specific inhibition of the H+/K+-ATPase in gastric parietal cells.",
      storage: "Store below 30°C, protected from moisture and light.",
      warnings: ["Pregnancy", "Kidney"],
      variants: [
        { label: "20 mg Capsule", strength: "20 mg", type: "Capsule" },
        { label: "40 mg Capsule", strength: "40 mg", type: "Capsule" },
        { label: "40 mg IV Injection", strength: "40 mg", type: "Injection" },
      ],
      status: "Approved",
    },
    {
      id: "m7",
      brand: "Maxpro",
      name: "Maxpro 20mg",
      type: "Tablet",
      strength: "20 mg",
      generic: "Esomeprazole Magnesium Trihydrate",
      company: "Renata Limited",
      companyId: "c6",
      price: "6.50 BDT",
      packSize: "5 x 10's pack",
      usage: "GERD, acid reflux, peptic ulcer.",
      dosage: "20 mg once daily.",
      sideEffects: "Mild headache, diarrhea.",
      indication: "GERD, healing of erosive oesophagitis, peptic ulcer disease, H. pylori eradication.",
      adultDose: "20–40 mg once daily for 4–8 weeks.",
      childDose: "12–17 years: 20–40 mg once daily.",
      renalDose: "No adjustment in mild to moderate impairment.",
      administration: "Take 1 hour before food. Swallow whole.",
      contraindications: "Hypersensitivity to esomeprazole.",
      precautions: "Long-term use risks similar to other PPIs.",
      pregnancy: "Category B. Caution in lactation.",
      interactions: "Reduces clopidogrel effect. Affects warfarin, methotrexate.",
      adverse: "Headache, diarrhea, nausea.",
      mechanism: "Inhibits gastric H+/K+-ATPase.",
      storage: "Store below 30°C, dry place.",
      warnings: ["Pregnancy"],
      variants: [
        { label: "20 mg Tablet", strength: "20 mg", type: "Tablet" },
        { label: "40 mg Tablet", strength: "40 mg", type: "Tablet" },
      ],
      status: "Approved",
    },
    {
      id: "m8",
      brand: "Fexo",
      name: "Fexo 120mg",
      type: "Tablet",
      strength: "120 mg",
      generic: "Fexofenadine Hydrochloride",
      company: "Square Pharmaceuticals Ltd.",
      companyId: "c2",
      price: "9.00 BDT",
      packSize: "3 x 10's pack",
      usage: "Seasonal allergic rhinitis, chronic urticaria.",
      dosage: "120 mg once daily or 60 mg twice daily.",
      sideEffects: "Headache, drowsiness (rare).",
      indication:
        "Seasonal allergic rhinitis, perennial allergic rhinitis, chronic idiopathic urticaria.",
      adultDose: "120 mg once daily or 60 mg twice daily.",
      childDose: "6–11 years: 30 mg twice daily. 2–5 years: 15 mg twice daily.",
      renalDose: "CrCl < 80 mL/min: reduce to 60 mg once daily.",
      administration: "Take with water on an empty stomach. Avoid fruit juices.",
      contraindications: "Hypersensitivity to fexofenadine.",
      precautions: "Caution in renal impairment, elderly.",
      pregnancy: "Category C. Use only if clearly needed.",
      interactions: "Antacids containing aluminium and magnesium reduce absorption. Erythromycin, ketoconazole increase levels.",
      adverse: "Headache, dizziness, nausea, drowsiness.",
      mechanism: "Selective peripheral H1-receptor antagonist. Non-sedating second-generation antihistamine.",
      storage: "Store below 30°C, dry place.",
      warnings: ["Kidney"],
      variants: [
        { label: "30 mg / 5 ml Suspension", strength: "30 mg/5 ml", type: "Suspension" },
        { label: "60 mg Tablet", strength: "60 mg", type: "Tablet" },
        { label: "120 mg Tablet", strength: "120 mg", type: "Tablet" },
        { label: "180 mg Tablet", strength: "180 mg", type: "Tablet" },
      ],
      status: "Approved",
    },
    {
      id: "m9",
      brand: "Amodis",
      name: "Amodis 400mg",
      type: "Tablet",
      strength: "400 mg",
      generic: "Metronidazole",
      company: "Square Pharmaceuticals Ltd.",
      companyId: "c2",
      price: "1.50 BDT",
      packSize: "10 x 10's pack",
      usage: "Anaerobic infections, amoebiasis, giardiasis.",
      dosage: "400 mg three times daily for 7 days.",
      sideEffects: "Metallic taste, nausea, dark urine.",
      indication: "Anaerobic bacterial infections, amoebiasis, giardiasis, trichomoniasis, bacterial vaginosis, H. pylori eradication.",
      adultDose: "400 mg three times daily for 5–7 days. Amoebiasis: 800 mg TDS for 5 days.",
      childDose: "7.5 mg/kg three times daily for 7 days.",
      renalDose: "No adjustment in renal impairment. Reduce dose in severe hepatic disease.",
      administration: "Take with or after food to reduce GI upset.",
      contraindications: "Hypersensitivity to nitroimidazoles. First trimester pregnancy.",
      precautions: "Avoid alcohol during and 48 hours after treatment (disulfiram-like reaction). Caution in hepatic disease.",
      pregnancy: "Avoid in first trimester. Category B in 2nd and 3rd trimesters.",
      interactions: "Disulfiram-like reaction with alcohol. Potentiates warfarin. Increases lithium and phenytoin levels.",
      adverse: "Metallic taste, nausea, headache, dark urine, peripheral neuropathy with prolonged use.",
      mechanism: "Disrupts DNA synthesis in anaerobic organisms via reduction to reactive intermediates.",
      storage: "Store below 30°C, protected from light.",
      warnings: ["Pregnancy", "Liver"],
      variants: [
        { label: "200 mg Tablet", strength: "200 mg", type: "Tablet" },
        { label: "400 mg Tablet", strength: "400 mg", type: "Tablet" },
        { label: "200 mg / 5 ml Suspension", strength: "200 mg/5 ml", type: "Suspension" },
        { label: "500 mg IV Infusion", strength: "500 mg/100 ml", type: "Infusion" },
      ],
      status: "Approved",
    },
    {
      id: "m10",
      brand: "Bizoral",
      name: "Bizoral 200mg",
      type: "Tablet",
      strength: "200 mg",
      generic: "Ketoconazole",
      company: "Beximco Pharmaceuticals Ltd.",
      companyId: "c1",
      price: "12.00 BDT",
      packSize: "1 x 10's pack",
      usage: "Systemic and superficial fungal infections.",
      dosage: "200 mg once daily.",
      sideEffects: "Nausea, headache, hepatotoxicity.",
      indication: "Systemic fungal infections (only when other antifungals not appropriate). Topical use for tinea, candidiasis, seborrhoeic dermatitis.",
      adultDose: "200 mg once daily, may increase to 400 mg if response inadequate.",
      childDose: "Over 2 years: 3.3–6.6 mg/kg once daily.",
      renalDose: "No adjustment required.",
      administration: "Oral with food to enhance absorption (requires gastric acidity).",
      contraindications: "Acute or chronic liver disease. Coadministration with terfenadine, astemizole, cisapride, statins.",
      precautions: "Hepatotoxicity (boxed warning). Monitor LFTs. QT prolongation risk.",
      pregnancy: "Category C. Avoid in pregnancy and breastfeeding.",
      interactions: "Strong CYP3A4 inhibitor — many serious interactions. Avoid statins, oral anticoagulants, midazolam.",
      adverse: "Nausea, vomiting, abdominal pain, hepatotoxicity, gynaecomastia.",
      mechanism: "Inhibits ergosterol synthesis by inhibiting fungal CYP450 14-α-demethylase, disrupting fungal cell membrane.",
      storage: "Store below 30°C, dry place.",
      warnings: ["Liver", "Pregnancy"],
      variants: [
        { label: "200 mg Tablet", strength: "200 mg", type: "Tablet" },
        { label: "2% Cream", strength: "2%", type: "Cream" },
        { label: "2% Shampoo", strength: "2%", type: "Shampoo" },
      ],
      status: "Approved",
    },
    {
      id: "m11",
      brand: "Reset",
      name: "Reset 500mg",
      type: "Tablet",
      strength: "500 mg",
      generic: "Paracetamol",
      company: "ACI Limited",
      companyId: "c5",
      price: "1.20 BDT",
      packSize: "20 x 10's pack",
      usage: "Fever, headache, body pain.",
      dosage: "500–1000 mg every 4–6 hours.",
      sideEffects: "Rare allergic reaction.",
      indication: "Fever, headache, mild to moderate pain.",
      adultDose: "500–1000 mg every 4–6 hours. Max 4 g/day.",
      childDose: "10–15 mg/kg every 4–6 hours.",
      renalDose: "Increase dosing interval in severe renal impairment.",
      administration: "Oral with or without food.",
      contraindications: "Severe hepatic dysfunction.",
      precautions: "Caution in chronic alcoholism.",
      pregnancy: "Category B.",
      interactions: "Warfarin potentiation with chronic use.",
      adverse: "Rash, rare hepatotoxicity in overdose.",
      mechanism: "Central COX inhibition.",
      storage: "Store below 30°C.",
      warnings: ["Liver"],
      variants: [
        { label: "120 mg / 5 ml Syrup", strength: "120 mg/5 ml", type: "Syrup" },
        { label: "500 mg Tablet", strength: "500 mg", type: "Tablet" },
      ],
      status: "Approved",
    },
    {
      id: "m12",
      brand: "Fimoxyl",
      name: "Fimoxyl 250mg",
      type: "Capsule",
      strength: "250 mg",
      generic: "Amoxicillin Trihydrate",
      company: "Opsonin Pharma Limited",
      companyId: "c7",
      price: "5.00 BDT",
      packSize: "10 x 10's pack",
      usage: "Bacterial infections of respiratory and urinary tract.",
      dosage: "250–500 mg every 8 hours.",
      sideEffects: "Diarrhea, rash.",
      indication: "Respiratory infections, otitis media, sinusitis, urinary tract infections, H. pylori eradication, dental abscesses.",
      adultDose: "250–500 mg every 8 hours or 500–875 mg every 12 hours.",
      childDose: "20–40 mg/kg/day in 3 divided doses.",
      renalDose: "CrCl 10–30 mL/min: every 12 hours. CrCl <10: every 24 hours.",
      administration: "Oral with or without food.",
      contraindications: "Penicillin hypersensitivity. History of severe hypersensitivity reactions.",
      precautions: "Monitor for superinfection. Cross-reactivity with cephalosporins.",
      pregnancy: "Category B. Generally safe in pregnancy and lactation.",
      interactions: "Probenecid increases amoxicillin levels. Reduces oral contraceptive efficacy. Allopurinol increases rash risk.",
      adverse: "Diarrhea, rash, nausea, candidiasis. Rare: anaphylaxis, Stevens-Johnson syndrome.",
      mechanism: "Beta-lactam antibiotic. Inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins.",
      storage: "Store below 30°C, dry place.",
      warnings: ["Kidney"],
      variants: [
        { label: "125 mg / 5 ml Suspension", strength: "125 mg/5 ml", type: "Suspension" },
        { label: "250 mg Capsule", strength: "250 mg", type: "Capsule" },
        { label: "500 mg Capsule", strength: "500 mg", type: "Capsule" },
      ],
      status: "Approved",
    },
    {
      id: "m13",
      brand: "Cetin",
      name: "Cetin 10mg",
      type: "Tablet",
      strength: "10 mg",
      generic: "Cetirizine Hydrochloride",
      company: "Incepta Pharmaceuticals Ltd.",
      companyId: "c4",
      price: "2.00 BDT",
      packSize: "10 x 10's pack",
      usage: "Allergic rhinitis, urticaria, allergic conjunctivitis.",
      dosage: "10 mg once daily.",
      sideEffects: "Drowsiness, dry mouth.",
      indication: "Seasonal and perennial allergic rhinitis, chronic urticaria, allergic conjunctivitis, atopic dermatitis.",
      adultDose: "10 mg once daily. Elderly or hepatic impairment: 5 mg once daily.",
      childDose: "6–11 years: 5–10 mg once daily. 2–5 years: 2.5 mg once or twice daily.",
      renalDose: "CrCl 30–49 mL/min: 5 mg once daily. CrCl <30: 5 mg every other day.",
      administration: "Take in the evening to reduce daytime drowsiness.",
      contraindications: "Hypersensitivity to cetirizine, hydroxyzine, or piperazine derivatives. Severe renal impairment with CrCl <10 mL/min.",
      precautions: "May cause drowsiness — caution while driving. Avoid alcohol.",
      pregnancy: "Category B. Excreted in breast milk; not recommended.",
      interactions: "CNS depressants and alcohol potentiate sedation. Theophylline reduces clearance.",
      adverse: "Drowsiness, dry mouth, fatigue, headache.",
      mechanism: "Selective peripheral H1-receptor antagonist. Second-generation antihistamine with minimal CNS penetration.",
      storage: "Store below 30°C, dry place.",
      warnings: ["Kidney"],
      variants: [
        { label: "5 mg / 5 ml Syrup", strength: "5 mg/5 ml", type: "Syrup" },
        { label: "10 mg Tablet", strength: "10 mg", type: "Tablet" },
        { label: "10 mg / ml Drops", strength: "10 mg/ml", type: "Drops" },
      ],
      status: "Approved",
    },
    {
      id: "m14",
      brand: "Pyrol",
      name: "Pyrol 500mg",
      type: "Tablet",
      strength: "500 mg",
      generic: "Paracetamol",
      company: "Renata Limited",
      companyId: "c6",
      price: "1.20 BDT",
      packSize: "10 x 10's pack",
      usage: "Fever, headache.",
      dosage: "500 mg every 4–6 hours.",
      sideEffects: "Rare rash.",
      indication: "Fever, mild to moderate pain.",
      adultDose: "500–1000 mg every 4–6 hours. Max 4 g/day.",
      childDose: "10–15 mg/kg every 4–6 hours.",
      renalDose: "Increase interval in severe impairment.",
      administration: "Oral, with or without food.",
      contraindications: "Severe hepatic dysfunction.",
      precautions: "Caution in alcohol abuse.",
      pregnancy: "Category B.",
      interactions: "Warfarin potentiation.",
      adverse: "Rare rash, hepatotoxicity in overdose.",
      mechanism: "Central COX inhibition.",
      storage: "Store below 30°C.",
      warnings: ["Liver"],
      variants: [
        { label: "120 mg / 5 ml Syrup", strength: "120 mg/5 ml", type: "Syrup" },
        { label: "500 mg Tablet", strength: "500 mg", type: "Tablet" },
      ],
      status: "Approved",
    },
    {
      id: "m15",
      brand: "Xpa",
      name: "Xpa 500mg",
      type: "Tablet",
      strength: "500 mg",
      generic: "Paracetamol",
      company: "Incepta Pharmaceuticals Ltd.",
      companyId: "c4",
      price: "1.20 BDT",
      packSize: "10 x 10's pack",
      usage: "Fever, pain relief.",
      dosage: "500 mg every 4–6 hours.",
      sideEffects: "Rare allergic rash.",
      indication: "Fever, headache, mild to moderate pain.",
      adultDose: "500–1000 mg every 4–6 hours.",
      childDose: "10–15 mg/kg every 4–6 hours.",
      renalDose: "Adjust interval in severe impairment.",
      administration: "Oral with or without food.",
      contraindications: "Severe hepatic disease.",
      precautions: "Caution in alcohol abuse.",
      pregnancy: "Category B.",
      interactions: "Warfarin.",
      adverse: "Rash, hepatotoxicity in overdose.",
      mechanism: "Central COX inhibition.",
      storage: "Store below 30°C.",
      warnings: ["Liver"],
      variants: [
        { label: "500 mg Tablet", strength: "500 mg", type: "Tablet" },
      ],
      status: "Approved",
    },
    {
      id: "m16",
      brand: "Brufen",
      name: "Brufen 400mg",
      type: "Tablet",
      strength: "400 mg",
      generic: "Ibuprofen",
      company: "Beximco Pharmaceuticals Ltd.",
      companyId: "c1",
      price: "2.50 BDT",
      packSize: "10 x 10's pack",
      usage: "Pain, inflammation, fever.",
      dosage: "400 mg every 6–8 hours as needed.",
      sideEffects: "Stomach upset, dyspepsia.",
      indication: "Mild to moderate pain, dysmenorrhea, rheumatoid arthritis, osteoarthritis, fever, post-operative pain.",
      adultDose: "200–400 mg every 4–6 hours. Max 1.2 g/day OTC, 2.4 g/day prescription.",
      childDose: "5–10 mg/kg every 6–8 hours. Max 40 mg/kg/day.",
      renalDose: "Avoid in severe renal impairment.",
      administration: "Take with food or milk to minimize GI upset.",
      contraindications: "Active peptic ulcer, severe heart failure, severe renal impairment, NSAID-induced asthma, third trimester pregnancy.",
      precautions: "Cardiovascular and GI risk. Use lowest effective dose for shortest duration.",
      pregnancy: "Avoid in third trimester (premature ductal closure). Category C/D.",
      interactions: "Reduces antihypertensive efficacy. Increases lithium, methotrexate levels. Increased bleeding with anticoagulants.",
      adverse: "GI upset, dyspepsia, peptic ulcer, renal impairment, hypertension, fluid retention.",
      mechanism: "Non-selective COX-1 and COX-2 inhibitor, reducing prostaglandin synthesis.",
      storage: "Store below 30°C, protected from light.",
      warnings: ["Pregnancy", "Kidney", "Liver"],
      variants: [
        { label: "100 mg / 5 ml Suspension", strength: "100 mg/5 ml", type: "Suspension" },
        { label: "200 mg Tablet", strength: "200 mg", type: "Tablet" },
        { label: "400 mg Tablet", strength: "400 mg", type: "Tablet" },
        { label: "600 mg Tablet", strength: "600 mg", type: "Tablet" },
      ],
      status: "Approved",
    },
  ],
  appointments: [
    {
      id: "a1",
      patientId: "p1",
      doctorId: "d1",
      hospitalId: "h1",
      date: new Date().toISOString().split("T")[0],
      time: "10:00",
      status: "Scheduled",
    },
    {
      id: "a2",
      patientId: "p2",
      doctorId: "d1",
      hospitalId: "h1",
      date: new Date().toISOString().split("T")[0],
      time: "11:30",
      status: "Scheduled",
    },
  ],
  prescriptions: [],
  icuPatients: [],
  icuPlans: [],
  nurseTasks: [],
  reports: [],
  beds: [
    { id: "b1", hospitalId: "h1", number: "ICU-01", occupied: false },
    { id: "b2", hospitalId: "h1", number: "ICU-02", occupied: false },
    { id: "b3", hospitalId: "h1", number: "ICU-03", occupied: false },
    { id: "b4", hospitalId: "h2", number: "ICU-01", occupied: false },
  ],
}

export const STORAGE_KEY = "healthcare_prototype_data_v2"
export const AUTH_KEY = "healthcare_prototype_auth_v1"
