// Initial seed data for the healthcare prototype
export const seedData = {
  hospitals: [
    { id: "h1", name: "MediCare General Hospital", city: "New York" },
    { id: "h2", name: "Riverside Medical Center", city: "Boston" },
  ],
  doctors: [
    {
      id: "d1",
      name: "Dr. Sarah Chen",
      specialty: "General Medicine",
      hospitalIds: ["h1", "h2"],
      phone: "555-0101",
    },
    {
      id: "d2",
      name: "Dr. Michael Roberts",
      specialty: "Cardiology",
      hospitalIds: ["h1"],
      phone: "555-0102",
    },
    {
      id: "d3",
      name: "Dr. Priya Patel",
      specialty: "Pediatrics",
      hospitalIds: ["h2"],
      phone: "555-0103",
    },
  ],
  nurses: [
    { id: "n1", name: "Nurse Emily Davis", hospitalId: "h1", shift: "Day" },
    { id: "n2", name: "Nurse James Wilson", hospitalId: "h1", shift: "Night" },
    { id: "n3", name: "Nurse Anna Lopez", hospitalId: "h2", shift: "Day" },
  ],
  patients: [
    {
      id: "p1",
      name: "John Smith",
      phone: "555-1001",
      age: 45,
      gender: "Male",
      createdAt: new Date().toISOString(),
    },
    {
      id: "p2",
      name: "Maria Garcia",
      phone: "555-1002",
      age: 32,
      gender: "Female",
      createdAt: new Date().toISOString(),
    },
  ],
  companies: [
    { id: "c1", name: "PharmaCorp Inc.", email: "info@pharmacorp.com" },
    { id: "c2", name: "MediGen Labs", email: "contact@medigen.com" },
  ],
  medicines: [
    {
      id: "m1",
      name: "Paracetamol 500mg",
      type: "Tablet",
      generic: "Acetaminophen",
      usage: "Pain relief and fever reduction",
      dosage: "1-2 tablets every 4-6 hours",
      sideEffects: "Rare allergic reactions",
      companyId: "c1",
      status: "Approved",
    },
    {
      id: "m2",
      name: "Amoxicillin 250mg",
      type: "Capsule",
      generic: "Amoxicillin",
      usage: "Bacterial infections",
      dosage: "1 capsule three times daily",
      sideEffects: "Nausea, diarrhea",
      companyId: "c1",
      status: "Approved",
    },
    {
      id: "m3",
      name: "Ibuprofen 400mg",
      type: "Tablet",
      generic: "Ibuprofen",
      usage: "Pain and inflammation",
      dosage: "1 tablet every 6-8 hours",
      sideEffects: "Stomach upset",
      companyId: "c2",
      status: "Approved",
    },
    {
      id: "m4",
      name: "Cetirizine 10mg",
      type: "Tablet",
      generic: "Cetirizine",
      usage: "Allergy relief",
      dosage: "1 tablet daily",
      sideEffects: "Drowsiness",
      companyId: "c2",
      status: "Pending",
    },
  ],
  appointments: [
    {
      id: "a1",
      patientId: "p1",
      doctorId: "d1",
      hospitalId: "h1",
      date: new Date().toISOString().split("T")[0],
      time: "10:00",
      status: "Scheduled",
    },
    {
      id: "a2",
      patientId: "p2",
      doctorId: "d1",
      hospitalId: "h1",
      date: new Date().toISOString().split("T")[0],
      time: "11:30",
      status: "Scheduled",
    },
  ],
  prescriptions: [],
  icuPatients: [],
  icuPlans: [],
  nurseTasks: [],
  reports: [],
  beds: [
    { id: "b1", hospitalId: "h1", number: "ICU-01", occupied: false },
    { id: "b2", hospitalId: "h1", number: "ICU-02", occupied: false },
    { id: "b3", hospitalId: "h1", number: "ICU-03", occupied: false },
    { id: "b4", hospitalId: "h2", number: "ICU-01", occupied: false },
  ],
}

export const STORAGE_KEY = "healthcare_prototype_data_v1"
export const AUTH_KEY = "healthcare_prototype_auth_v1"
